/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    users: User
    media: Media
    realisations: Realisation
    services: Service
    engagements: Engagement
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  db: {
    defaultIDType: number
  }
  globals: {
    home: Home
    contact: Contact
  }
  locale: null
  user: User & {
    collection: 'users'
  }
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

export interface User {
  id: number
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}

export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}

export interface Realisation {
  id: number
  title: string
  subtitle?: string | null
  cover_image: number | Media
  gallery?: {
    image: number | Media
    id?: string | null
  }[] | null
  slug: string
  order?: number | null
  published?: boolean | null
  featured?: boolean | null
  lieu?: string | null
  surface?: number | null
  duree?: string | null
  annee?: number | null
  type_intervention?: ('renovation_complete' | 'renovation_partielle' | 'amenagement' | 'restauration') | null
  architecte_associe?: string | null
  photographe?: string | null
  narration?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  points_cles?: {
    texte: string
    id?: string | null
  }[] | null
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: number
  num?: string | null
  title: string
  description: string
  order?: number | null
  updatedAt: string
  createdAt: string
}

export interface Engagement {
  id: number
  title: string
  description: string
  order?: number | null
  updatedAt: string
  createdAt: string
}

export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?: {
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
}

export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}

export interface Home {
  id: number
  hero_image?: number | Media | null
  intro_text?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  comprehension_text?: string | null
  citation_texte?: string | null
  citation_auteur_nom?: string | null
  citation_auteur_titre?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}

export interface Contact {
  id: number
  cta_title?: string | null
  cta_subtitle?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  calendar_url?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
